### ISSUE TITLE
Figure out why edits take long

### ISSUE THREAD

**Issue by pimotte** [impermeable/waterproof-vscode#117]

**Comment by pimotte** [comment]
Some findings on my machine:

Using gitpod:
- Desyncs can happen, but are relatively hard to trigger. Skulls are easily triggered on flaky internet.
- editor.ts/setLineNumbers takes a large amount of CPU time. Attached profile shows the situation on flaky internet 

Using a local install and throttling internet using the vscode dev tools to "Slow 4G"
- Unable to cause desyncs
- Skulls can happen

Errors when skull happens:

```
editor.ts:176  Mapping does not contain this position, is node inserted in middle of another node?
dispatchTransaction @ editor.ts:176
dispatch @ index.js:5690
(anonymous) @ index.js:408
handleHistoryChange @ editor.ts:341
(anonymous) @ index.ts:67
postMessage
(anonymous) @ index.html?id=b24567ef-ebbc-44f8-a156-38623887c90c&origin=fda03a83-efcb-4610-b12d-6a7716ff6d52&swVersion=4&extensionId=waterproof-tue.waterproof&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1229
HostMessaging.channel.port1.onmessage @ index.html?id=b24567ef-ebbc-44f8-a156-38623887c90c&origin=fda03a83-efcb-4610-b12d-6a7716ff6d52&swVersion=4&extensionId=waterproof-tue.waterproof&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:322
Show 2 more frames
Show less
notificationsAlerts.ts:42 File frozen due to corruption. Re-open the file. Error:  Mapping does not contain this position, is node inserted in middle of another node?
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
B @ event.ts:1243
C @ event.ts:1254
fire @ event.ts:1278
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
editor.ts:496 Uncaught Error: Diagnostic message does not match any coqblock
    at Editor.parseCoqDiagnostics (editor.ts:496:26)
    at Editor.handleMessage (editor.ts:526:10)
    at index.ts:70:15
parseCoqDiagnostics @ editor.ts:496
handleMessage @ editor.ts:526
(anonymous) @ index.ts:70
postMessage
(anonymous) @ index.html?id=b24567ef-ebbc-44f8-a156-38623887c90c&origin=fda03a83-efcb-4610-b12d-6a7716ff6d52&swVersion=4&extensionId=waterproof-tue.waterproof&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1229
HostMessaging.channel.port1.onmessage @ index.html?id=b24567ef-ebbc-44f8-a156-38623887c90c&origin=fda03a83-efcb-4610-b12d-6a7716ff6d52&swVersion=4&extensionId=waterproof-tue.waterproof&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:322
```

Using a local install and throttling internet using the vscode dev tools to "3G"
- Causes "goals request interrupted" rejected promise to bubble
- Same issues as 4G
- Sometimes the checker is shut down because of "errors in the connection" (could not reproduce at time of writing this)

Using a local install and simulating a slow harddrive with a block device with latency:
- When backspacing, sometimes the backspace gets rewound (i.e. characters that were just removed reappear).
- No problematic issues (desyncs/skulls)

How to simulate a slow hard drive:

Set up a loopback device as described [here](https://serverfault.com/questions/523509/linux-how-to-simulate-hard-disk-latency-i-want-to-increase-iowait-value-withou) and Use `mkfs -t ext4 -v /dev/loop<number here>` to create a file system on the loopback device before mapping it with dmsetup. Finally, mount the mapped device.
